# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './form1.ui'
#
# Created: Tue Jun  4 13:26:08 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(866, 707)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 851, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.category_id = QtGui.QComboBox(self.gridLayoutWidget)
        self.category_id.setObjectName("category_id")
        self.gridLayout.addWidget(self.category_id, 1, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.altname = QtGui.QLineEdit(self.gridLayoutWidget)
        self.altname.setObjectName("altname")
        self.gridLayout.addWidget(self.altname, 1, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.region_id = QtGui.QComboBox(self.gridLayoutWidget)
        self.region_id.setObjectName("region_id")
        self.gridLayout.addWidget(self.region_id, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.refreshButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.refreshButton.setObjectName("refreshButton")
        self.gridLayout.addWidget(self.refreshButton, 0, 5, 1, 1)
        self.title = QtGui.QLineEdit(self.gridLayoutWidget)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 1, 1, 4)
        self.district = QtGui.QLineEdit(self.gridLayoutWidget)
        self.district.setObjectName("district")
        self.gridLayout.addWidget(self.district, 2, 3, 1, 3)
        self.partner_id = QtGui.QComboBox(self.gridLayoutWidget)
        self.partner_id.setObjectName("partner_id")
        self.gridLayout.addWidget(self.partner_id, 1, 1, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 140, 851, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 2, 1, 1)
        self.material = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.material.setObjectName("material")
        self.gridLayout_2.addWidget(self.material, 0, 8, 1, 1)
        self.year = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.year.setObjectName("year")
        self.gridLayout_2.addWidget(self.year, 1, 5, 1, 1)
        self.plan = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.plan.setObjectName("plan")
        self.gridLayout_2.addWidget(self.plan, 1, 1, 1, 1)
        self.price = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.price.setObjectName("price")
        self.gridLayout_2.addWidget(self.price, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.apartmentstate = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.apartmentstate.setObjectName("apartmentstate")
        self.gridLayout_2.addWidget(self.apartmentstate, 1, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 4, 1, 1)
        self.space = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.space.setObjectName("space")
        self.gridLayout_2.addWidget(self.space, 0, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.balcony = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.balcony.setObjectName("balcony")
        self.gridLayout_2.addWidget(self.balcony, 2, 3, 1, 1)
        self.phone = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.phone.setObjectName("phone")
        self.gridLayout_2.addWidget(self.phone, 2, 5, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 0, 1, 1)
        self.ontop = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.ontop.setObjectName("ontop")
        self.gridLayout_2.addWidget(self.ontop, 3, 6, 1, 1)
        self.isactive = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.isactive.setObjectName("isactive")
        self.gridLayout_2.addWidget(self.isactive, 3, 5, 1, 1)
        self.imageurl = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.imageurl.setObjectName("imageurl")
        self.gridLayout_2.addWidget(self.imageurl, 3, 1, 1, 3)
        self.floor = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.floor.setObjectName("floor")
        self.gridLayout_2.addWidget(self.floor, 0, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 6, 1, 1)
        self.conditionbuilding = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.conditionbuilding.setObjectName("conditionbuilding")
        self.gridLayout_2.addWidget(self.conditionbuilding, 2, 1, 1, 2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 120, 871, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 290, 871, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 310, 851, 311))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.text_desc = QtGui.QPlainTextEdit(self.gridLayoutWidget_3)
        self.text_desc.setObjectName("text_desc")
        self.gridLayout_3.addWidget(self.text_desc, 0, 2, 2, 1)
        self.imageLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayout_3.addWidget(self.imageLabel, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(680, 630, 171, 26))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 866, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Заголовок", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Партнер", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Категория", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Altname", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Город", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Район", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshButton.setText(QtGui.QApplication.translate("MainWindow", "Обновить", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Цена", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Состояние\n"
" помещения", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Площадь", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Состояние\n"
" дома", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Год постройки", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Этаж", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Планировка", None, QtGui.QApplication.UnicodeUTF8))
        self.balcony.setText(QtGui.QApplication.translate("MainWindow", "Балкон", None, QtGui.QApplication.UnicodeUTF8))
        self.phone.setText(QtGui.QApplication.translate("MainWindow", "Телефон", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Картинка", None, QtGui.QApplication.UnicodeUTF8))
        self.ontop.setText(QtGui.QApplication.translate("MainWindow", "На главной", None, QtGui.QApplication.UnicodeUTF8))
        self.isactive.setText(QtGui.QApplication.translate("MainWindow", "Активно", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Материал", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.imageLabel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

